apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.dev.shapeblock.com
spec:
  group: dev.shapeblock.com
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    singular: project
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              name:
                type: string
                description: The human readable name of the project.
              description:
                type: string
                description: What this project is about.
            type: object
    served: true
    storage: true
    subresources:
      status: {}
