apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: paketo-python
spec:
  sources:
  - image: index.docker.io/paketobuildpacks/python
  - image: index.docker.io/paketobuildpacks/nodejs
  - image: index.docker.io/shapeblock/chmod:0.0.5
