apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: sb-php
spec:
  sources:
  - image: index.docker.io/paketobuildpacks/ca-certificates
  - image: index.docker.io/paketobuildpacks/php-dist
  - image: index.docker.io/paketobuildpacks/composer
  - image: registry.gitlab.com/shapeblock-buildpacks/composer-install:0.0.1
  - image: index.docker.io/paketobuildpacks/nginx
  - image: index.docker.io/paketobuildpacks/php-fpm
  - image: registry.gitlab.com/shapeblock-buildpacks/php-nginx:0.0.1
  - image: index.docker.io/paketobuildpacks/php-start
  - image: index.docker.io/paketobuildpacks/nodejs
  - image: index.docker.io/paketobuildpacks/procfile
  - image: index.docker.io/shapeblock/apt:0.3.1
  - image: index.docker.io/shapeblock/chmod:0.0.5
